language: node_js

before_install:
  - npm install

jobs:
  include:
    - name: Backend Test
      if: $TRAVIS_BRANCH = qa 
      script:
        - npm test -- --detectOpenHandles


deploy:
  provider: heroku
  api_key: 
    - secure: $HEROKU_API_KEY
  app: innovin
  on:
    branch: main
