services:
  db:
    image: mysql
    container_name: innovin
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  innovin-backend:
    container_name: innovin-backend
    build: .
    image: innovin-backend
    depends_on:
      - db
    ports:
      - 8888:8888
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TIMING: 1h
      UPLOADS_FOLDER: ${UPLOADS_FOLDER}
    links:
      - db
    volumes:
      - ./:/express-js
volumes:
  db_data:
    driver: local


    docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' c74d85589979