name: CD Pipeline

on:
  push:
    branches:
      - amin
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker image
        run: docker tag myapp:latest ${{ steps.build.outputs.ecr-url }}:latest

      - name: Push Docker image to AWS ECR
        run: docker push ${{ steps.build.outputs.ecr-url }}:latest
