name: CI Pipeline

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0' 

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Test
        run: npm test -- --detectOpenHandles