name: Continuous Integration

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        restart: always
        ports:
          - '3308:3306'
        env:
          MYSQL_DATABASE: innovin
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test -- --detectOpenHandles
