name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env: 
       DB_HOST: 172.20.0.2
       DB_NAME: innovin
       DB_USER: innovin
       DB_PASSWORD: innovin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test -- --detectOpenHandles
