name: Continuous Integration

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env: 
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: innovin
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test -- --detectOpenHandles
