name: Continuous Integration

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: database
          MYSQL_ROOT_PASSWORD: toto
        ports:
          - '3308:3306'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Dependencies and Build
        run: 
          npm install

      - name: Run Backend Tests
        run: npm test -- --detectOpenHandles

        env: 
          MYSQL_DATABASE: innovin
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_PORT: 3308
          MYSQL_USER: root
